### ISSUE TITLE
c4doc_enumerateAllDocs not honoring includeDeleted

### ISSUE THREAD

**Issue by borrrden** [couchbaselabs/cbforest#34]
Unit test [here](https://gist.github.com/borrrden/eb3f275021fe46c7bedc)

The all docs enumerator is including deleted documents no matter what.

**Comment by borrrden** [comment]
Guess I should put more details in here.  The default options have includeDeleted as false.  This is running on the CppTests target on Xcode 7 / El Capitan.

**Comment by snej** [comment]
Yeah, CBForest just uses the ForestDB include-deleted flag. Which isn't very useful for documents because we never delete them except on a purge. Our notion of deleted is just a flag in the metadata.

The Obj-C codebase does the filtering itself during the all-docs query; see CBL_ForestDBStorage.mm lines 632-634.

It would probably be useful to put this logic in the C API.

**Comment by borrrden** [comment]
It might be easier to leave it up to the other side, and just eliminate the includeDeleted parameter on the options.  It only adds another line or two to C# to check (it has to check documents anyway in certain situations to make sure that design docs are not included)

**Comment by snej** [comment]
I'm already implementing it, actually. It's more efficient to skip docs at a lower level. While I'm at it, I should add the 'only-conflicts' flag too.
